language: python
sudo: required
dist: xenial
python: "3.7"

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - env: TOXENV=py37-pytest38
    - env: TOXEND=py37-pytest39

install:
  - pip install tox

script:
  - tox
